"""Added properties tables for orders and trucks

Revision ID: 81a3fc320492
Revises: 71a29236c06a
Create Date: 2020-10-06 23:05:56.231151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a3fc320492'
down_revision = '71a29236c06a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('truck_properties',
    sa.Column('s_number', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['s_number'],
                            ['truck.s_number'],
                            ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('s_number', 'key')
    )
    op.create_table('order_properties',
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_number'],
                            ['order.order_number'],
                            ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_number', 'key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_properties')
    op.drop_table('truck_properties')
    # ### end Alembic commands ###
