"""First version

Revision ID: b5565fa100b8
Revises:
Create Date: 2020-09-14 15:11:02.363777

"""
from alembic import op
import sqlalchemy as sa
from backend.models import User


# revision identifiers, used by Alembic.
revision = 'b5565fa100b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = op.create_table(
                    'user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username',
                              sa.String(length=40),
                              nullable=False),
                    sa.Column('password',
                              sa.LargeBinary(length=60),
                              nullable=False),
                    sa.Column('role', sa.String(length=20),
                              nullable=False,
                              server_default='view-only'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )

    # Add an initial user

    admin = User('admin', 'admin', 'administrator')

    op.bulk_insert(user_table, [
        {'username': admin.username,
         'password': admin.password,
         'role': admin.role}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
