"""Added unique index to username

Revision ID: b6954ffedcc5
Revises: b5565fa100b8
Create Date: 2020-09-15 17:39:28.790926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6954ffedcc5'
down_revision = 'b5565fa100b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_username',
                    'user',
                    [sa.text('lower(username)')],
                    unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    # ### end Alembic commands ###
