"""Created planning model

Revision ID: cdfe68f8509c
Revises: 81a3fc320492
Create Date: 2020-10-19 13:59:50.957704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdfe68f8509c'
down_revision = '81a3fc320492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planning',
    sa.Column('order_sheet_id', sa.Integer(), nullable=False),
    sa.Column('truck_sheet_id', sa.Integer(), nullable=False),
    sa.Column('published_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_sheet_id'], ['order_sheet.id'], ),
    sa.ForeignKeyConstraint(['truck_sheet_id'], ['truck_sheet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('order_sheet_id', 'truck_sheet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planning')
    # ### end Alembic commands ###
